Update playwright.yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -52,11 +52,11 @@ jobs:
           nohup node server.js > ../server.log 2>&1 &
           sleep 5
 
-      - name: Wait for backend to be ready
-        run: |
-          npx wait-on http://localhost:5000/api || (
-            echo "❌ Backend failed to start, showing server.log:" && cat backend/server.log && exit 1
-          )
+      # - name: Wait for backend to be ready
+      #   run: |
+      #     npx wait-on http://localhost:5000/api || (
+      #       echo "❌ Backend failed to start, showing server.log:" && cat backend/server.log && exit 1
+      #     )
 
       - name: Install Playwright
         run: npx playwright install --with-deps
